MyMovie/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
import xadmin
from django.views.static import serve
from users.views import RegisterView, IndexView, FaceLoginView
from movie.views import MoviePlayView, MovieTagView, SearchView, MovieReleasetimeView, MoviePlaynumsView, MovieMarkView, \
    MovieCommentView
from users import views as users_view
from movie import views as movie_view
from MyMovie import settings
from rest_framework.documentation import include_docs_urls

'''
as_view()调用函数,会根据请求方式,返回对应的函数名；

'''
urlpatterns = [
    # 普通django后台管理
    # url(r'^admin/', admin.site.urls),

    # 超级后台
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view()),
    # 主页
    url(r'^index/', IndexView.as_view(), name='index'),
    # 电影标签分类接口
    url(r'^movietag/$', MovieTagView.as_view(), name='movietag'),
    # 评分分类接口
    url(r'^moviemark/$', MovieMarkView.as_view(), name='moviemark'),
    # 上映时间分类接口
    url(r'^moviereleasetime/$', MovieReleasetimeView.as_view(), name='moviereleasetime'),
    # 播放量分类接口
    url(r'^movieplaynums/$', MoviePlaynumsView.as_view(), name='movieplaynums'),
    # 评论数分类接口
    url(r'^moviecomments/$', MovieCommentView.as_view(), name='moviecomments'),

    # 注册
    url(r'^register/$', RegisterView.as_view(), name='register'),

    # 人脸注册
    # url(r'^faceregister/$', FaceRegisterView.as_view(), name='faceregister'),

    # 判断性别
    url(r'^gender/', users_view.gender, name='gender'),

    # 获取验证码(极验滑动验证码)
    url(r'^pc-geetest/register/', users_view.get_slidecode, name='get_slidecode'),
    # 极验滑动验证码登录
    url(r'^slide_login/', users_view.SlideLoginView.as_view(), name='slide_login'),
    url(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),  # 配置media文件夹

    # 人脸登录
    url(r'face_login/', FaceLoginView.as_view(), name='face_login'),

    # 获取验证码(手动)
    url(r'^get_code/', users_view.get_code, name='get_code'),
    # 图片验证码登录
    url(r'login/$', users_view.LoginView.as_view(), name='login'),

    # 注销
    url(r'^logout/$', users_view.logout, name='logout'),

    # 搜索
    url(r'^search/$', SearchView.as_view(), name='search'),

    # 播放电影
    url(r'^play/(?P<movie_id>.*)/$', MoviePlayView.as_view(), name='play'),

    # 用户评论
    url(r'^comment/$', movie_view.comment, name='comment'),
    # 影评
    url(r'^filmreview/$', movie_view.film_review, name='filmreview'),

    # 收藏电影
    url(r'^colmovie/$', movie_view.colmovie, name='colmovie'),

    # 个人中心
    url(r'^users/', include('users.urls', namespace='users')),
    # url(r'^userinfo/', UserInfoView.as_view(), name='userinfo'),

    # 接口文档
    url(r'^docs/', include_docs_urls(title='时光网的文档')),

]

apps/users/urls.py
from django.conf.urls import url
from users.views import UserInfoView, ForgetView, CommentListView, LoginLogView, FavMovieView

urlpatterns = [
    # 个人中心
    url(r'^userinfo/$', UserInfoView.as_view(), name='userinfo'),
    # 修改密码
    url('forget/pwd/', ForgetView.as_view(), name='forget_pwd'),
    # 评论记录
    url(r'^comment/$', CommentListView.as_view(), name='comment'),
    # 登录日志
    url(r'^log/$', LoginLogView.as_view(), name='login_log'),
    # 收藏电影
    url(r'^fav_movie/$', FavMovieView.as_view(), name='fav_movie')
]

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>我爬电影养你啊</title>
    <!--样式-->
    <link rel="stylesheet" href="{% static 'base/css/bootstrap-3.3.7.min.css' %}">
    <link rel="stylesheet" href="http://static1.mtime.cn/nodewww/2019051313312/css/common/public.css">
    <link rel="stylesheet" href="http://static1.mtime.cn/nodewww/2019051313312/css/index/index.css">
    <!--js脚本-->
    <script src="{% static 'base/js/jQuery-3.4.1.js' %}"></script>
    <script src="{% static 'base/js/bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base/js/npm.js' %}"></script>
    <script src="{% static 'base/js/wow.min.js' %}"></script>
    <script src="{% static 'base/js/jquery.min.js' %}"></script>
{#    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>#}
    {#    <script src="http://static1.mtime.cn/nodewww/2019051313312/js/common/common-index.js"></script>#}
    <script src="{% static 'js/common-index.js' %}"></script>

    <script>
        var api_server = "api-data-channel.jx.mtime-prd.com"
            , extra_api_server = "web.channel.mtime.com"
            , css_server = "static1.mtime.cn/nodewww"
            , js_server = "static1.mtime.cn/nodewww"
            , img_server = "img31.mtime.cn"
            , img_proxyUrl = "http://img31.mtime.cn/get.ashx"
            , server = "www.mtime.com"
            , site_domain = ".mtime.com"
            , site_domain_cn = ".mtime.cn"
            , site_server = "www.mtime.com"
            , rev = "/2019051313312"
            , MT = "M18";
    </script>

    <style>
        .navbar-brand > img {
            display: inline;
        }
    </style>

    {% block css %}

    {% endblock %}
</head>
<body>

<!--导航条开始-->
<nav class="navbar navbar-inverse" style="background-color: #192332">
    <div class="container-fluid">
        <!--左侧跑马灯开始-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'index' %}" style="width: 250px">
                <marquee behavior="scroll" direction="right">
                    万佩佩的电影时光
                </marquee>
            </a>

        </div>
        <!--左侧跑马灯结束-->

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <!-- 中间索引开始 -->
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'index' %}">首页<span class="sr-only">(current)</span></a></li>
                <li><a href="#">排行榜</a></li>
                <li><a href="#">影评</a></li>
            </ul>
            <form class="navbar-form navbar-left" action="{% url 'search' %}">
                <div class="form-group">
                    <input type="text" name="keywords" class="form-control" placeholder="想看啥">
                </div>
                <button type="submit" class="btn btn-default" style="background-color: white">搜索</button>
            </form>
            <ul class="nav navbar-nav" style="margin-left: 70px">
                <li><a href="#"><b style="font-family: Tahoma,Arial;font-size: large">For people who love movies</b></a>
                </li>
            </ul>
            <!-- 中间索引结束 -->
            <!--右侧登录注册开始-->
            <ul class="nav navbar-nav navbar-right">
                <!--如果认证通过则显示用户的信息-->
                {% if request.user.is_authenticated %}
                    <li><a href="">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">其他功能<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'users:userinfo' %}">个人中心</a></li>
                            <li><a href="/logout/">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}
            </ul>
            <!--右侧登录注册结束-->
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!--导航条结束-->

<!--中间主体-->
<div class="container">
    {% block content %}

    {% endblock %}
</div>


<!--底部开始-->
<div class="footout"><span class="topline"></span>
    <br>
    <div class="fotlogo">
        <marquee behavior="scroll" direction="right">
            <dt><a href="#" title="Mtime时光网">Mtime时光网</a>
        </marquee>
        </dt>

        <div class="db_foot"><p>
            <h1>有任何问题请联系站长 @万佩佩</h1>
            <span>不知道接不接的站长电话：15151979063   联系邮箱：616130272@qq.com</span><br/><span>上海万佩佩科技有限公司</span>Copyright
            2006-2019 Mtime.com Inc. All rights reserved.<br/><a href="http://feature.mtime.com/help/icp.htm"
                                                                 target="_blank">京ICP证050715号</a><a
                    href="http://feature.mtime.com/help/videolicence.htm" target="_blank"
                    class="mr12">网络视听许可证0108265号</a><a
                    href="http://feature.mtime.com/help/network.htm" target="_blank" class="mr12">网络文化经营许可证</a><a
                    href="http://feature.mtime.com/help/tvlicence.htm" target="_blank"
                    class="mr12">广播电视节目制作经营许可证(京)字第1435号</a><a
        </div>
        <!--底部结束-->
    </div>
</div>
{% block js %}

{% endblock %}

</body>
</html><!--expire:Thu Jan 01 1970 08:00:00 GMT+0800 (CST)-->

templates/face_login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>人脸识别登录</title>
    <link rel="stylesheet" href="{% static 'base/css/bootstrap-3.3.7.min.css' %}">
    {#    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>#}
    <script src="{% static 'base/js/jQuery-3.4.1.js' %}"></script>
    <script src="{% static 'jQuery-webcam-master/jquery.webcam.min.js' %}"></script>

    <style type="text/css">
        #video {
            border: 1px solid #666666;
            width: 277px;
            height: 240px;
        }

        #canvas {
            border: 1px solid #666666;
            width: 277px;
            height: 240px;
        }
    </style>

</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h3 class="text-center">人脸登录</h3>

            <hr>
            <div id="contentHolder" style="text-align: center">
                <!--标签定义视频，比如电影片段或其他视频流-->
                <video id="video" width="270" height="320" autoplay style="border-radius: 50px"></video>
                <!--标签定义图形，比如图表和其他图像,标签只是图形容器，您必须使用脚本来绘制图形-->
                <canvas id="canvas" width="270" height="320" name="imagecontent" style="border-radius: 50px" hidden></canvas>
                <br>
                <button id="start" class="btn btn-success">开启摄像头</button>
                <button id="stop" class="btn btn-danger">关闭摄像头</button>
                <br>
                <br>
                <button id="login" class="btn btn-info" >登录</button>
                <span class="errors" style="color: palevioletred" id="id_error"></span>

            </div>
        </div>
    </div>
</div>
</body>



<!--人脸识别操作开始-->
<script>

    var mediaStreamTrack;
    // 点击开始按钮，开启摄像头
    $('#start').click(() => {
        navigator.getUserMedia = navigator.getUserMedia ||
            navigator.webkitGetUserMedia ||
            navigator.mozGetUserMedia;
        if (navigator.getUserMedia) {
            navigator.getUserMedia({audio: true, video: {width: 320, height: 320}},
                function (stream) {
                    mediaStreamTrack = typeof stream.stop === 'function' ? stream : stream.getTracks()[1];
                    // video.src = (window.URL || window.webkitURL).createObjectURL(stream);
                    // video.play();

                    // 将摄像头内容放在视频标签中
                    var video = document.getElementById("video");
                    //将视频流转化为video的源
                    video.srcObject = stream;
                    try {
                        this.srcObject = stream;
                    } catch (error) {
                        this.src = window.URL.createObjectURL(stream);
                    }
                    video.src = (window.URL || window.webkitURL).createObjectURL(stream);
                    video.onloadedmetadata = function (e) {
                        console.log('nihao44eee4aaaaddda');
                        video.play();
                    };
                },
                function (err) {
                    console.log("The following error occurred: " + err.name);
                }
            );
        } else {
            console.log("getUserMedia not supported");
        }
    });
    // 点击结束按钮，关闭摄像头
    $('#stop').click(() => {
        mediaStreamTrack && mediaStreamTrack.stop();
    });

    // 点击登录按钮进行拍照
    {#$('#login').click(() => {#}
    {#    var context = document.getElementById("canvas").getContext("2d");#}
    {#    context.drawImage(video, 0, 0, 270, 320);#}
    {# });#}

    // 对图像进行编码(后期优化在后端编码解码)
    function getBase64Image(img) {
        var canvastemp = document.createElement("canvas");
        canvastemp.width = img.width;
        canvastemp.height = img.height;
        var ctx = canvas.getContext("2d");
        ctx.drawImage(img, 0, 0, img.width, img.height);
        var dataURL = canvas.toDataURL("image/png");
        return dataURL
        // return dataURL.replace("data:image/png;base64,", "");
    }

    //点击登录同时完成两件事，拍照并登录
    $('#login').click(function () {
        // 拍照
        let context = document.getElementById("canvas").getContext("2d");
        context.drawImage(video, 0, 0, 270, 320);
        let imgData = document.getElementById("canvas").toDataURL("image/png");
        var mmmd = getBase64Image(document.getElementById("canvas"));
        var data = imgData.substr(22);
        console.log(mmmd);  // 带头data:image/png;base64,iVBO
        console.log(data);  // 不带头，只有编码iVBORw0KGgoAAAANSUhEUgAAAQ4AAAF
        $.ajax({
            url: '',
            type: 'post',
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                'imagecontent': mmmd,
            },
            success: function (data) {
                if (data.code == 100) {
                    location.href = data.url
                } else {
                    $('#id_error').html(data.msg);
                }
            }
        })
    })
</script>
<!--人脸识别操作结束-->


</html>

templates/film_review.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb" style="margin-top:6px; background-color: lightgoldenrodyellow; height: 40px">
                </ol>
            </div>
            <div class="col-md-12">

                {% for movie in movie_obj %}
                    <div class="media">
                        <div class="media-left">
                            <a href="play.html">
                                {#                                <img class="media-object" src="{{ MEDIA_URL }}{{ movie.logo }}" alt="环太平洋">#}
                                <img class="media-object" src="/media/{{ movie.logo }}" alt=""
                                     style="height: 150px;width: 100px">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">{{ movie.title }}<a href="{% url 'play' movie.id %}"
                                                                          class="label label-warning pull-right">
                                <span class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                            <br>
                        【影评】{{ movie.info }}
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            </div>

            <div class="col-md-12 text-center">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if movies.has_previous %}
                            <li>
                                <a href="?{{ movies.previous_page_number.querystring }}" aria-label="Previous">
                                    <span aria-hidden="true">上一页</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for page in movies.pages %}
                            {% if page %}
                                {% ifequal page movies.number %}
                                    <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                {% endifequal %}
                            {% else %}
                                <li class="none"><a href="">...</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if movies.has_next %}
                            <li>
                                <a href="?{{ movies.next_page_number.querystring }}" aria-label="Next">
                                    <span aria-hidden="true">下一页</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>

{% endblock %}

templates/forgetpwd.html
{% extends 'base.html' %}

{% block content %}

    <div class="container" style="margin-top:76px">
        <!--左侧边栏-->
        {% include 'menu.html' %}
        <!--右边主体开始-->
        <div class="col-md-9">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;修改密码</h3>
                </div>
                <div class="panel-body">
                    <fieldset>
                        <form id="myform">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="input_newpwd">
                                    <span class="glyphicon glyphicon-lock"></span>&nbsp;输入新密码</label>
                                <input id="input_newpwd" class="form-control" placeholder="输入新密码" name="new_password"
                                       type="password" autofocus>
                                <span class="errors pull-right" style="color:palevioletred" id="error1"></span>
                            </div>
                            {#                        <div class="col-md-12" id="error_newpwd"></div>#}
                            <div class="form-group">
                                <label for="input_conpwd">
                                    <span class="glyphicon glyphicon-lock"></span>&nbsp;确认新密码</label>
                                {#                            <span class="errors" style="color: palevioletred" id="id_error"></span>#}

                                <input id="input_conpwd" class="form-control" placeholder="再次输入密码"
                                       name="confirm_password"
                                       type="password" autofocus>
                                <span class="errors pull-right" style="color:palevioletred" id="error2"></span>
                            </div>
                            <div class="errors" id="id_error" style="color: palevioletred"></div>
                        </form>
                        <button class="btn btn-lg btn-success btn-block" id="submit-btn">修改密码</button>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            $('#m-2').addClass('active')
        });

        //ajax发送数据
        $('#submit-btn').click(function () {
            let new_password = $('#input_newpwd').val();
            let confirm_password = $('#input_conpwd').val();
            $.ajax({
                url: '',
                type: 'post',
                data: {
                    new_password,
                    confirm_password,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function (data) {
                    if (data.code == 100) {
                        location.href = data.url  // 如果成功跳转到登录界面
                    } else {
                        //console.log(data.msg);
                        if (data.msg.new_password) {
                            $('#error1').html(data.msg.new_password[0]).parent().addClass('has-error')
                        }
                        if (data.msg.confirm_password) {
                            $('#error2').html(data.msg.confirm_password[0]).parent().addClass('has-error')

                        }

                    }
                }
            });
            $('input').focus(function () {
                $(this).next().html('').parent().removeClass('has-error')
            });

        })
    </script>
{% endblock %}

templates/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a href="{% url 'users:userinfo' %}" id="m-1" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&emsp;&emsp;个人中心
        </a>
        <a href="{% url 'users:forget_pwd' %}" id="m-2" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&emsp;&emsp;修改密码
        </a>
        <a href="{% url 'users:comment' %}" id="m-3" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&emsp;&emsp;评论记录
        </a>
        <a href="{% url 'users:login_log' %}" id="m-4" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&emsp;&emsp;登录日志
        </a>
        <a href="{% url 'users:fav_movie' %}" id="m-5" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&emsp;&emsp;收藏电影
        </a>
    </div>
</div>